name: npm-pkg-lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  npm-pkg-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/npm-pkg-lint
          key: npm-pkg-lint
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run --if-present build
      - name: Pack
        run: npm pack
      - name: npm-pkg-lint
        run: npm exec npm-pkg-lint
